spring:
  context-path: /temis-server
  profiles.active: local
---
spring:
  profiles: local
  
  data:
   mongodb:
    uri: mongodb://localhost/temisdb
---

year.start.extract: 2013
url.laws: http://www.ceaam.net/sjc/legislacao/leis/
url.aldermen: http://www.camarasjc.sp.gov.br/vereadores/
path.leis: src/main/resources/data/html/